/**
 * Mesh generation module.
 *
 * Takes a depth map (grayscale image) and generates a 3D mesh as both
 * OBJ and GLB formats. The mesh is a displaced grid where each vertex's
 * Z position corresponds to the depth value at that pixel.
 */

import sharp from "sharp";

interface MeshData {
  obj: string;
  glb: Buffer;
}

/**
 * Generate OBJ and GLB mesh data from a depth map.
 *
 * @param depthMapBase64 - Base64 data-URL of the grayscale depth map
 * @param originalImageBase64 - Base64 data-URL of the original image (for texture coords)
 * @param resolution - Grid resolution (default 128x128)
 * @param depthScale - How much to extrude depth (default 0.3)
 */
export async function generateMesh(
  depthMapBase64: string,
  originalImageBase64: string,
  resolution: number = 128,
  depthScale: number = 0.3
): Promise<MeshData> {
  // Decode depth map
  const depthB64 = depthMapBase64.replace(/^data:image\/\w+;base64,/, "");
  const depthBuffer = Buffer.from(depthB64, "base64");

  // Get raw pixel data from depth map
  const { data: depthPixels } = await sharp(depthBuffer)
    .grayscale()
    .resize(resolution, resolution, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Generate vertices, UVs, normals, and faces
  const vertices: number[][] = [];
  const uvs: number[][] = [];
  const faces: number[][] = [];

  const width = resolution;
  const height = resolution;

  // Create vertex grid
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = y * width + x;
      const depth = depthPixels[idx] / 255.0;

      // Map to [-1, 1] range for X and Y, depth for Z
      const vx = (x / (width - 1)) * 2 - 1;
      const vy = -((y / (height - 1)) * 2 - 1); // Flip Y
      const vz = depth * depthScale;

      vertices.push([vx, vy, vz]);

      // UV coordinates
      const u = x / (width - 1);
      const v = 1 - y / (height - 1);
      uvs.push([u, v]);
    }
  }

  // Create faces (two triangles per grid cell)
  for (let y = 0; y < height - 1; y++) {
    for (let x = 0; x < width - 1; x++) {
      const tl = y * width + x;
      const tr = tl + 1;
      const bl = (y + 1) * width + x;
      const br = bl + 1;

      // Triangle 1: top-left, bottom-left, bottom-right
      faces.push([tl, bl, br]);
      // Triangle 2: top-left, bottom-right, top-right
      faces.push([tl, br, tr]);
    }
  }

  // Compute normals
  const normals = computeNormals(vertices, faces);

  // Generate OBJ string
  const obj = generateOBJ(vertices, uvs, normals, faces);

  // Generate GLB binary
  const glb = generateGLB(vertices, uvs, normals, faces);

  return { obj, glb };
}

/**
 * Compute per-vertex normals by averaging face normals.
 */
function computeNormals(
  vertices: number[][],
  faces: number[][]
): number[][] {
  const normals: number[][] = vertices.map(() => [0, 0, 0]);

  for (const face of faces) {
    const [i0, i1, i2] = face;
    const v0 = vertices[i0];
    const v1 = vertices[i1];
    const v2 = vertices[i2];

    // Edge vectors
    const e1 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]];
    const e2 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]];

    // Cross product
    const n = [
      e1[1] * e2[2] - e1[2] * e2[1],
      e1[2] * e2[0] - e1[0] * e2[2],
      e1[0] * e2[1] - e1[1] * e2[0],
    ];

    // Accumulate
    for (const idx of face) {
      normals[idx][0] += n[0];
      normals[idx][1] += n[1];
      normals[idx][2] += n[2];
    }
  }

  // Normalize
  for (const n of normals) {
    const len = Math.sqrt(n[0] * n[0] + n[1] * n[1] + n[2] * n[2]);
    if (len > 0) {
      n[0] /= len;
      n[1] /= len;
      n[2] /= len;
    } else {
      n[2] = 1; // Default normal pointing up
    }
  }

  return normals;
}

/**
 * Generate OBJ format string.
 */
function generateOBJ(
  vertices: number[][],
  uvs: number[][],
  normals: number[][],
  faces: number[][]
): string {
  const lines: string[] = [];
  lines.push("# Generated by Pic3D - 2D to 3D converter");
  lines.push(`# Vertices: ${vertices.length}`);
  lines.push(`# Faces: ${faces.length}`);
  lines.push("");

  // Vertices
  for (const v of vertices) {
    lines.push(`v ${v[0].toFixed(6)} ${v[1].toFixed(6)} ${v[2].toFixed(6)}`);
  }
  lines.push("");

  // Texture coordinates
  for (const uv of uvs) {
    lines.push(`vt ${uv[0].toFixed(6)} ${uv[1].toFixed(6)}`);
  }
  lines.push("");

  // Normals
  for (const n of normals) {
    lines.push(`vn ${n[0].toFixed(6)} ${n[1].toFixed(6)} ${n[2].toFixed(6)}`);
  }
  lines.push("");

  // Faces (OBJ is 1-indexed)
  for (const f of faces) {
    const faceStr = f
      .map((idx) => `${idx + 1}/${idx + 1}/${idx + 1}`)
      .join(" ");
    lines.push(`f ${faceStr}`);
  }

  return lines.join("\n");
}

/**
 * Generate a minimal GLB (binary glTF 2.0) file.
 */
function generateGLB(
  vertices: number[][],
  uvs: number[][],
  normals: number[][],
  faces: number[][]
): Buffer {
  // Flatten arrays for binary buffer
  const positions = new Float32Array(vertices.length * 3);
  const texcoords = new Float32Array(uvs.length * 2);
  const normalArr = new Float32Array(normals.length * 3);
  const indices = new Uint32Array(faces.length * 3);

  // Compute bounding box
  let minX = Infinity, minY = Infinity, minZ = Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;

  for (let i = 0; i < vertices.length; i++) {
    const [x, y, z] = vertices[i];
    positions[i * 3] = x;
    positions[i * 3 + 1] = y;
    positions[i * 3 + 2] = z;
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    minZ = Math.min(minZ, z);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
    maxZ = Math.max(maxZ, z);
  }

  for (let i = 0; i < uvs.length; i++) {
    texcoords[i * 2] = uvs[i][0];
    texcoords[i * 2 + 1] = uvs[i][1];
  }

  for (let i = 0; i < normals.length; i++) {
    normalArr[i * 3] = normals[i][0];
    normalArr[i * 3 + 1] = normals[i][1];
    normalArr[i * 3 + 2] = normals[i][2];
  }

  for (let i = 0; i < faces.length; i++) {
    indices[i * 3] = faces[i][0];
    indices[i * 3 + 1] = faces[i][1];
    indices[i * 3 + 2] = faces[i][2];
  }

  // Build binary buffer
  const posBuffer = Buffer.from(positions.buffer);
  const texBuffer = Buffer.from(texcoords.buffer);
  const normBuffer = Buffer.from(normalArr.buffer);
  const idxBuffer = Buffer.from(indices.buffer);

  const totalBinLength =
    posBuffer.length + texBuffer.length + normBuffer.length + idxBuffer.length;

  // Pad to 4-byte alignment
  const binPadding = (4 - (totalBinLength % 4)) % 4;
  const binLength = totalBinLength + binPadding;

  const binData = Buffer.alloc(binLength);
  let offset = 0;
  idxBuffer.copy(binData, offset);
  offset += idxBuffer.length;
  posBuffer.copy(binData, offset);
  offset += posBuffer.length;
  normBuffer.copy(binData, offset);
  offset += normBuffer.length;
  texBuffer.copy(binData, offset);

  // Build JSON
  const idxByteOffset = 0;
  const posByteOffset = idxBuffer.length;
  const normByteOffset = posByteOffset + posBuffer.length;
  const texByteOffset = normByteOffset + normBuffer.length;

  const gltf = {
    asset: { version: "2.0", generator: "Pic3D" },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [
      {
        primitives: [
          {
            attributes: {
              POSITION: 1,
              NORMAL: 2,
              TEXCOORD_0: 3,
            },
            indices: 0,
          },
        ],
      },
    ],
    accessors: [
      {
        // indices
        bufferView: 0,
        componentType: 5125, // UNSIGNED_INT
        count: faces.length * 3,
        type: "SCALAR",
        max: [vertices.length - 1],
        min: [0],
      },
      {
        // positions
        bufferView: 1,
        componentType: 5126, // FLOAT
        count: vertices.length,
        type: "VEC3",
        max: [maxX, maxY, maxZ],
        min: [minX, minY, minZ],
      },
      {
        // normals
        bufferView: 2,
        componentType: 5126,
        count: normals.length,
        type: "VEC3",
      },
      {
        // texcoords
        bufferView: 3,
        componentType: 5126,
        count: uvs.length,
        type: "VEC2",
      },
    ],
    bufferViews: [
      {
        buffer: 0,
        byteOffset: idxByteOffset,
        byteLength: idxBuffer.length,
        target: 34963, // ELEMENT_ARRAY_BUFFER
      },
      {
        buffer: 0,
        byteOffset: posByteOffset,
        byteLength: posBuffer.length,
        target: 34962, // ARRAY_BUFFER
      },
      {
        buffer: 0,
        byteOffset: normByteOffset,
        byteLength: normBuffer.length,
        target: 34962,
      },
      {
        buffer: 0,
        byteOffset: texByteOffset,
        byteLength: texBuffer.length,
        target: 34962,
      },
    ],
    buffers: [{ byteLength: binLength }],
  };

  const jsonStr = JSON.stringify(gltf);
  const jsonBuffer = Buffer.from(jsonStr, "utf8");
  const jsonPadding = (4 - (jsonBuffer.length % 4)) % 4;
  const paddedJsonBuffer = Buffer.alloc(jsonBuffer.length + jsonPadding, 0x20); // pad with spaces
  jsonBuffer.copy(paddedJsonBuffer);

  // GLB header: magic + version + length
  // Chunk 0: JSON
  // Chunk 1: BIN
  const headerSize = 12;
  const jsonChunkHeaderSize = 8;
  const binChunkHeaderSize = 8;
  const totalLength =
    headerSize +
    jsonChunkHeaderSize +
    paddedJsonBuffer.length +
    binChunkHeaderSize +
    binData.length;

  const glbBuffer = Buffer.alloc(totalLength);
  let pos = 0;

  // Header
  glbBuffer.writeUInt32LE(0x46546c67, pos); // magic: "glTF"
  pos += 4;
  glbBuffer.writeUInt32LE(2, pos); // version
  pos += 4;
  glbBuffer.writeUInt32LE(totalLength, pos); // total length
  pos += 4;

  // JSON chunk
  glbBuffer.writeUInt32LE(paddedJsonBuffer.length, pos); // chunk length
  pos += 4;
  glbBuffer.writeUInt32LE(0x4e4f534a, pos); // chunk type: "JSON"
  pos += 4;
  paddedJsonBuffer.copy(glbBuffer, pos);
  pos += paddedJsonBuffer.length;

  // BIN chunk
  glbBuffer.writeUInt32LE(binData.length, pos); // chunk length
  pos += 4;
  glbBuffer.writeUInt32LE(0x004e4942, pos); // chunk type: "BIN\0"
  pos += 4;
  binData.copy(glbBuffer, pos);

  return glbBuffer;
}
